/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Index;

import core.AmountCalculator;
import core.Calculator;
import core.Display;
import core.FactorialCalculator;
import core.Largest;
import core.LoginSystem;
import core.McqQuestion;
import core.MonthCalendar;
import core.MultiplicationTables;
import core.NumberChecker;
import core.PowerRaiser;
import core.QuadraticEqSolver;
import core.StudentInfo;
import core.VotingEligibilityChecker;
import core.VowelCheckerForm;

/**
 *
 * @author GAMER
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form nextform
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        subHeading = new javax.swing.JLabel();
        powerRaise = new javax.swing.JButton();
        qudratic = new javax.swing.JButton();
        studentInfo = new javax.swing.JButton();
        voting = new javax.swing.JButton();
        vowelChecker = new javax.swing.JButton();
        amtCalc = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        display = new javax.swing.JButton();
        calendar = new javax.swing.JButton();
        mcq = new javax.swing.JButton();
        login = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        multiTables = new javax.swing.JButton();
        largest = new javax.swing.JButton();
        numChecker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(204, 0, 51));
        heading.setText("WELCOME TO INDEX PAGE");
        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 17));

        subHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subHeading.setText("Select the program to run:");
        getContentPane().add(subHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 279, -1));

        powerRaise.setBackground(new java.awt.Color(255, 255, 255));
        powerRaise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        powerRaise.setText("Power Raise Calculator");
        powerRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerRaiseActionPerformed(evt);
            }
        });
        getContentPane().add(powerRaise, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 346, -1));

        qudratic.setBackground(new java.awt.Color(255, 255, 255));
        qudratic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qudratic.setText("Quadratic Equation Solver");
        qudratic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qudraticActionPerformed(evt);
            }
        });
        getContentPane().add(qudratic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 346, -1));

        studentInfo.setBackground(new java.awt.Color(255, 255, 255));
        studentInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentInfo.setText("Student Info Register");
        studentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoActionPerformed(evt);
            }
        });
        getContentPane().add(studentInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 346, -1));

        voting.setBackground(new java.awt.Color(255, 255, 255));
        voting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        voting.setText("Voting Eligibility Checker");
        voting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votingActionPerformed(evt);
            }
        });
        getContentPane().add(voting, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 346, -1));

        vowelChecker.setBackground(new java.awt.Color(255, 255, 255));
        vowelChecker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vowelChecker.setText("Vowel Checker Form");
        vowelChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vowelCheckerActionPerformed(evt);
            }
        });
        getContentPane().add(vowelChecker, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 346, -1));

        amtCalc.setBackground(new java.awt.Color(255, 255, 255));
        amtCalc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amtCalc.setText("Amount Calculator");
        amtCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtCalcActionPerformed(evt);
            }
        });
        getContentPane().add(amtCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 346, -1));

        calc.setBackground(new java.awt.Color(255, 255, 255));
        calc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calc.setText("Calculator");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        getContentPane().add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 346, 30));

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 346, -1));

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calendar.setText("Month Calendar");
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });
        getContentPane().add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 346, -1));

        mcq.setBackground(new java.awt.Color(255, 255, 255));
        mcq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mcq.setText("MCQ Question");
        mcq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcqActionPerformed(evt);
            }
        });
        getContentPane().add(mcq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 346, -1));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("Login System");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 346, -1));

        factorial.setBackground(new java.awt.Color(255, 255, 255));
        factorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        factorial.setText("Factorial Calculator");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });
        getContentPane().add(factorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 346, -1));

        multiTables.setBackground(new java.awt.Color(255, 255, 255));
        multiTables.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multiTables.setText("Multiplication Tables");
        multiTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiTablesActionPerformed(evt);
            }
        });
        getContentPane().add(multiTables, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 346, -1));

        largest.setBackground(new java.awt.Color(255, 255, 255));
        largest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        largest.setText("Largest Number of 3");
        largest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largestActionPerformed(evt);
            }
        });
        getContentPane().add(largest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 346, -1));

        numChecker.setBackground(new java.awt.Color(255, 255, 255));
        numChecker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numChecker.setText("Number Checker");
        numChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCheckerActionPerformed(evt);
            }
        });
        getContentPane().add(numChecker, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 346, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amtCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtCalcActionPerformed
        AmountCalculator  amt =new AmountCalculator();
       amt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_amtCalcActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
       Display  frame =new Display();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_displayActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       LoginSystem  frame =new LoginSystem();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginActionPerformed

    private void multiTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiTablesActionPerformed
       MultiplicationTables  frame =new MultiplicationTables();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_multiTablesActionPerformed

    private void qudraticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qudraticActionPerformed
       QuadraticEqSolver  frame =new QuadraticEqSolver();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_qudraticActionPerformed

    private void vowelCheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vowelCheckerActionPerformed
       VowelCheckerForm  frame =new VowelCheckerForm();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vowelCheckerActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
       Calculator  frame =new Calculator();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_calcActionPerformed

    private void largestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largestActionPerformed
       Largest  frame =new Largest();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_largestActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
       FactorialCalculator  frame =new FactorialCalculator();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_factorialActionPerformed

    private void mcqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcqActionPerformed
        McqQuestion  amt =new McqQuestion();
       amt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mcqActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
       MonthCalendar  frame =new MonthCalendar();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_calendarActionPerformed

    private void numCheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCheckerActionPerformed
       NumberChecker  frame =new NumberChecker();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_numCheckerActionPerformed

    private void powerRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerRaiseActionPerformed
       PowerRaiser  frame =new PowerRaiser();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_powerRaiseActionPerformed

    private void studentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoActionPerformed
       StudentInfo  frame =new StudentInfo();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentInfoActionPerformed

    private void votingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votingActionPerformed
       VotingEligibilityChecker frame =new VotingEligibilityChecker();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_votingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amtCalc;
    private javax.swing.JButton calc;
    private javax.swing.JButton calendar;
    private javax.swing.JButton display;
    private javax.swing.JButton factorial;
    private javax.swing.JLabel heading;
    private javax.swing.JButton largest;
    private javax.swing.JButton login;
    private javax.swing.JButton mcq;
    private javax.swing.JButton multiTables;
    private javax.swing.JButton numChecker;
    private javax.swing.JButton powerRaise;
    private javax.swing.JButton qudratic;
    private javax.swing.JButton studentInfo;
    private javax.swing.JLabel subHeading;
    private javax.swing.JButton voting;
    private javax.swing.JButton vowelChecker;
    // End of variables declaration//GEN-END:variables
}
