package core;

import Index.Index;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GAMER
 */
public class AmountCalculator extends javax.swing.JFrame {

    /**
     * Creates new form sd
     */
    public AmountCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        L1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        SUBTRACT = new javax.swing.JButton();
        MULTIPLY = new javax.swing.JButton();
        DIVIDE = new javax.swing.JButton();
        MODULO = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 119, 86, 38));

        L1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 117, 44, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("=");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 117, -1, -1));

        CLEAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 116, 106, 39));

        ADD.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ADD.setText("+");
        ADD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PLUSfocusgain(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 206, -1, -1));

        SUBTRACT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SUBTRACT.setText("-");
        SUBTRACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBTRACTActionPerformed(evt);
            }
        });
        getContentPane().add(SUBTRACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 206, -1, -1));

        MULTIPLY.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MULTIPLY.setText("*");
        MULTIPLY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLYActionPerformed(evt);
            }
        });
        getContentPane().add(MULTIPLY, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 206, -1, -1));

        DIVIDE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DIVIDE.setText("/");
        DIVIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVIDEActionPerformed(evt);
            }
        });
        getContentPane().add(DIVIDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 212, -1, 48));

        MODULO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MODULO.setText("%(modulo)");
        MODULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODULOActionPerformed(evt);
            }
        });
        getContentPane().add(MODULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 218, -1, 43));

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 108, 160, 53));

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 105, 42));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("CALCULATOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Index/home.png"))); // NOI18N
        home.setToolTipText("Go Back to Index Page");
        home.setBorderPainted(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        t1.setText("");
        t2.setText("");
        t3.setText("");
        L1.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        L1.setText("+");
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        double c = a+b;
        t3.setText(""+c);
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void SUBTRACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBTRACTActionPerformed
        L1.setText("-");
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        double c = a-b;
        t3.setText(""+c);
    }//GEN-LAST:event_SUBTRACTActionPerformed

    private void MULTIPLYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLYActionPerformed
        L1.setText("*");
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        double c = a*b;
        t3.setText(""+c);       
    }//GEN-LAST:event_MULTIPLYActionPerformed

    private void DIVIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVIDEActionPerformed
        L1.setText("/");
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        float c = (float) (a / b);
        t3.setText(""+c);         
    }//GEN-LAST:event_DIVIDEActionPerformed

    private void MODULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODULOActionPerformed
        L1.setText("%");
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        double c = a % b ;
        t3.setText(""+c); 
    }//GEN-LAST:event_MODULOActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void PLUSfocusgain(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PLUSfocusgain
        // TODO add your handling code here:
    }//GEN-LAST:event_PLUSfocusgain

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       Index  frame =new Index();
       frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmountCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmountCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmountCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmountCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmountCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DIVIDE;
    private javax.swing.JLabel L1;
    private javax.swing.JButton MODULO;
    private javax.swing.JButton MULTIPLY;
    private javax.swing.JButton SUBTRACT;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
