package core;

import Index.Index;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Calculator.java
 *
 * Created on 9 Jul, 2015, 8:26:58 PM
 */

/**
 *
 * @author GAMER
 */
public class Calculator extends javax.swing.JFrame {
    

    /** Creates new form CALCULATOR */
    public Calculator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterprice = new javax.swing.JLabel();
        entrqtypurchased = new javax.swing.JLabel();
        SaleAmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        netpayableamount = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        RESET = new javax.swing.JButton();
        COMPUTE = new javax.swing.JButton();
        discount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        basic = new javax.swing.JButton();
        home = new javax.swing.JButton();

        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextPane3ComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(jTextPane3);

        jTextPane4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextPane4ComponentShown(evt);
            }
        });
        jScrollPane4.setViewportView(jTextPane4);

        jTextPane6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextPane6ComponentShown(evt);
            }
        });
        jScrollPane6.setViewportView(jTextPane6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATE YOUR BILL");
        setBackground(java.awt.Color.blue);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 0, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        jLabel1.setText("CALCULATE YOUR BILL ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 490, 89));

        enterprice.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        enterprice.setForeground(new java.awt.Color(0, 0, 153));
        enterprice.setText("Enter Price Of Item");
        jPanel1.add(enterprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 31));

        entrqtypurchased.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        entrqtypurchased.setForeground(new java.awt.Color(0, 0, 153));
        entrqtypurchased.setText("Enter qty Purchased");
        jPanel1.add(entrqtypurchased, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 27));

        SaleAmount.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        SaleAmount.setForeground(new java.awt.Color(0, 0, 153));
        SaleAmount.setText("Sale Amount");
        jPanel1.add(SaleAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 245, -1));

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Today`s Offer is FLAT 10% OFF!!!!!!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 31));

        t1.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setToolTipText("Enter the price of the item which you purchased");
        t1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                hhh(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 106, 44));

        t2.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setToolTipText("Here your Number of items Purcahsed is Required");
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enter(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 67, 40));

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 105, 38));

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel10.setText("$");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 24, 31));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel3.setText("$");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 24, 31));

        netpayableamount.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        netpayableamount.setForeground(new java.awt.Color(0, 0, 153));
        netpayableamount.setText("NET payable amount");
        jPanel1.add(netpayableamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, 40));

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 80, 40));

        RESET.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        RESET.setText("RESET");
        RESET.setToolTipText("Clears all entered Values.\nMostly useful When a Second Attempt Is made");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel1.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 110, 32));

        COMPUTE.setBackground(new java.awt.Color(51, 0, 51));
        COMPUTE.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        COMPUTE.setForeground(new java.awt.Color(0, 204, 102));
        COMPUTE.setText("COMPUTE");
        COMPUTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPUTEActionPerformed(evt);
            }
        });
        jPanel1.add(COMPUTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 185, 32));

        discount.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        discount.setForeground(new java.awt.Color(0, 0, 153));
        discount.setText("DISCOUNT");
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel12.setText("$");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 24, 31));

        t5.setEditable(false);
        t5.setFont(new java.awt.Font("Aharoni", 1, 36)); // NOI18N
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 98, 42));

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel11.setText("$");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 24, 31));

        jLabel4.setText(" ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 860, 440));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 360));

        basic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        basic.setText("BASIC CALCULATIONS");
        basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicActionPerformed(evt);
            }
        });
        jPanel1.add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 240, 60));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Index/home.png"))); // NOI18N
        home.setToolTipText("Go Back to Index Page");
        home.setBorderPainted(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPane3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextPane3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane3ComponentShown

    private void jTextPane4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextPane4ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane4ComponentShown

    private void jTextPane6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextPane6ComponentShown

    }//GEN-LAST:event_jTextPane6ComponentShown

    private void COMPUTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPUTEActionPerformed
        double PRICE = Double.parseDouble(t1.getText());
        double QUANTITY = Double.parseDouble(t2.getText());
        double SALE = PRICE * QUANTITY;
        double DISC = 10*SALE/100;
        double FINAL = SALE - DISC;

        t3.setText(""+SALE);
        t4.setText(""+DISC);
        t5.setText(""+FINAL);
     
}//GEN-LAST:event_COMPUTEActionPerformed

    private void hhh(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_hhh
    // TODO add your handling code here:
    }//GEN-LAST:event_hhh

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
      t1.setText("");
      t2.setText("");
      t3.setText("");
      t4.setText("");
      t5.setText(""); 
    }//GEN-LAST:event_RESETActionPerformed

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter

    }//GEN-LAST:event_enter

    private void basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicActionPerformed
AmountCalculator frame2 =new AmountCalculator();
Calculator.this.setVisible(true);
frame2.setVisible(true);
    }//GEN-LAST:event_basicActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Index  frame =new Index();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COMPUTE;
    private javax.swing.JButton RESET;
    private javax.swing.JLabel SaleAmount;
    private javax.swing.JButton basic;
    private javax.swing.JLabel discount;
    private javax.swing.JLabel enterprice;
    private javax.swing.JLabel entrqtypurchased;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JLabel netpayableamount;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
private javax.swing.JTextField app;

}